### ISSUE TITLE
Rationalise all the ARM template parameters to simplify. 

### ISSUE THREAD

**Issue by martinpeck** [opencb/opencga#1024]
For example if both HDInsight and Avere need an SSH key combine into single param.

Also ensure all params are in param file.

**Comment by lawrencegripper** [comment]
For SSH access all machines have been moved to using an SSH Key for access, with the one exception being HDInsights. 

This is because it's connected to directly from the `initContainer` as part of the setup. I had a look at the `setup.py` and I think we should avoid migrating this to a SSHKey. The concern I would have is that, as we've moved to using a single SSH key for the template, providing both the public and private part of the key to the template seems nasty. 

It would mean the `initContainer` would have the ability to connect to any of the machines in the deployment and the box it ran on would also hold the private key on disk. So for the time being I've stuck with using a separate password for the connection between the `initContainer` and the `hbase cluster`. Does this sound sensible?

For the passwords required in the template I've moved to taking in a parameter of `passwordGenerationData`. This provides a private value from which we can use `uniqueString` to derive separate passwords for each service. This differs from the approach [in the original mongo](https://github.com/bart-jansen/opencga/blob/29d30ff2486c4810bb02a370a70c834f7bdc3156/opencga-app/app/scripts/azure/arm/mongodb/azuredeploy.json#L44) template which used two bits of public information to generate the password (ResourceGroup Name and random data stored in the template). 

The generated passwords are then outputted as a `secureobject` along with the `adminUsername` which is now standardized across all services. 

The result of these combined changes is that the minimum set of parameters is currently:

```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "_artifactsLocation": {
            "value": "https://raw.githubusercontent.com/lawrencegripper/opencga/lg/issue/1024/opencga-app/app/scripts/azure/arm/"
        },
        "_artifactsLocationSasToken": {
            "value": "?125"
        },
        "HDInsightStorageOption": {
            "value": "DataLake"
        },
        "rgPrefix": {
            "value": "opencga10"
        },
        "rgLocation": {
            "value": "uksouth"
        },
        "avereServicePrincipalAppId": {
            "value": "spidhere"
        },
        "avereServicePrincipalPassword": {
            "value": "sppasswordhere"
        },
        "passwordGenerationData": {
            "value": "Somerandomentropyhere"
        },
        "sshAdminKeyData": {
            "value": "yourkeyhere"
        },
        "nfsStorageOption": {
            "value": "AzureFiles"
        },
        "mongoCertificateEmail": {
            "value": "some@email.here"
        },
        "tomcatDockerImage": {
            "value": "dotjson/opencga-app:azure"
        },
        "ivaDockerImage": {
            "value": "dotjson/iva:test"
        },
        "batchDockerImage": {
            "value": "dotjson/opencga-daemon:azure"
        },
        "initContainerImage": {
            "value": "dotjson/opencga-init:azure"
        },
        "daemonContainerImage": {
            "value": "dotjson/opencga-daemon:azure"
        }
    }
}
```

Of the remaining parameters:
- The `*Image` params can be defaulted once #1011 is in place with public images hosted on DockerHub. 
- The `artifacts*` params can be removed once #1018 is in place and inline's scripts and assets

Given this I think that once the changes in the PR #1045 are completed this item can be considered closed. What does everyone think? (@jjcollinge @martinpeck @marrobi)

**Comment by marrobi** [comment]
Looking good. 

If the passwords are securestring objects how will the end user know what they are? I'm not convinced by the approach, worried users will not know the credentials and will cause a support headache. feels over complicated. Maybe one to discuss?

We do not want to be passing private ssh keys if at all possible, so agree with HD Insights needing a pw.

Are you suggesting all scripts to be included in the template JSON? Some are quite lengthy... I'd in two minds around if makes more sense to download them when needed or to have inline. Pros and cons to each.

**Comment by lawrencegripper** [comment]
Good spot, currently I output them from the object as a `secureobject` but will need to move them to `object` so users can view them. 

My take is that a user deploying the template is going to be reliant on viewing the outputs to connect to systems (PublicIP/DNS of endpoints, SSH details for boxes etc) so having the passwords output doesn't add a burden as they're already going to need to look at the outputs ... plus the outputs remain available in the portal after a deployment has finished...but happy to be overruled.
