### ISSUE TITLE
New tools in OpenCGA Analysis

### ISSUE THREAD

**Issue by aaleman** [opencb/opencga#132]
How could we add new tools to OpenCGA analysis? Is it possible?

**Comment by imedina** [comment]
This question is timely, I'm organizing and upgrading the 'tools' ('analysis' folder before) in "feature/refactoring-conf" branch which will be merge into develop soon, you can take a look here:
https://github.com/opencb/opencga/tree/feature/refactoring-conf/opencga-app/build/tools

Which tools would you like to add? If the tools are not too big (~MB) you can create a well named folder and add it, otherwise let me know which are required. Also, just a reminder, you can always install them in your local OpnCGA installation.
