### ISSUE TITLE
Problem listing files

### ISSUE THREAD

**Issue by roalva1** [opencb/opencga#134]
I am not able of listing files, neither from the <code>files</code> interface:
http://bioinfoint.hpc.cam.ac.uk/opencga/rest/files/59/list?sid=nIpURd8aoPltKh21nhhw

Nor from the <code>studies</code> interface:
http://bioinfoint.hpc.cam.ac.uk/opencga/rest/studies/58/files?sid=nIpURd8aoPltKh21nhhw

**Comment by imedina** [comment]
After debugging a bit the problem seems to be here, in the Tomcat log: 

org.opencb.opencga.catalog.exceptions.CatalogDBException: java.lang.IllegalArgumentException: No enum constant org.opencb.opencga.catalog.db.api.CatalogFileDBAdaptor.FileFilterOption.sid at org.opencb.opencga.catalog.db.mongodb.CatalogMongoDBAdaptor.searchFile(CatalogMongoDBAdaptor.java:1443) at org.opencb.opencga.catalog.managers.FileManager.readAll(FileManager.java:333)
...

Is looking for 'sid' parameter here:

https://github.com/opencb/opencga/blob/develop/opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/CatalogMongoDBAdaptor.java#L1405

which not exist:

https://github.com/opencb/opencga/blob/develop/opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/api/CatalogFileDBAdaptor.java#L16

and the exception is launched. A quick fix is to skip 'sid' parameter from file fitlering.

**Comment by imedina** [comment]
The quick fix works fine, it is at:

https://github.com/opencb/opencga/blob/develop/opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/CatalogMongoDBAdaptor.java#L1402

now the URL works:

http://bioinfoint.hpc.cam.ac.uk/opencga/rest/files/59/list?sid=nIpURd8aoPltKh21nhhw

A better fix is needed.

**Comment by imedina** [comment]
This has been improved a little bit, this will improved in the future.
