### ISSUE TITLE
GT values in Negative 

### ISSUE THREAD

**Issue by Mohammedhusen** [opencb/opencga#1516]
Hi Team,

We could see some of variants records shows get values in negative for instance as below.

"0/1" : [ 
                "1/1" : [ 
                "-1/-1" : [ 
                "-1/0" : [ 
                "-1/1" : [

What exactly negative sign indicate here .

**Comment by j-coll** [comment]
You may have seen those values in the database, right?
In MongoDB, you can not store keys with "dots". In order to store genotypes like `./.`, `./0` or `./1` we replace the dot with `-1`

This should be transparent for the end-users. Please, let me know if you found these values in another place than MongoDB.

**Comment by Mohammedhusen** [comment]
Thank you !!
Really appreciate your quick response on this.
