### ISSUE TITLE
Same sample names in different vcfs for the same study

### ISSUE THREAD

**Issue by roalva1** [opencb/opencga#158]
When you index two vcf with the same sample names, the sample ids refer to the first vcf, this raise problems when filtering. For instance in this json: 

<pre>http://bioinfoint.hpc.cam.ac.uk/opencga/rest/files/2998/info?sid=8dBvCHgdIUUnTqRPBnEz</pre>

the field samplesIds refer to samples that belong to other file. As this is not correct, it seems that there are to approximations:
1. Save the ids correctly. 
2. It is said that opencga shouldn't index two vcf with the same samples names and the same regions, as I think this request will be done somehow from a user, opencga could raise a message telling that the requested action is not possible (always telling an understandable message ).

**Comment by j-coll** [comment]
There are no problem with having the same sample in multiple files. Indeed, it's an interesting feature, because you can track all the files where a sample appears. As you can see in the next query, sample 2988 appears in 4 different files:

    http://bioinfoint.hpc.cam.ac.uk/opencga/rest/files/search?sampleIds=2988&studyId=2&sid=8dBvCHgdIUUnTqRPBnEz

Doing this way, you can have the same sample (`HG001`) in one FASTQ, two different BAMs (as a result of 2 different alignments), and then 2 VCFs (`file1.vcf`, `file2.vcf`), one from each BAM. All this files will refer to the same sampleId. 

If you have 2 different files that refers to a 2 different samples with the same name (either different samples from the same individual or totally different samples) is considered a mistake. You will have to rename some sample to be differentiated.

The main problem here is to try to index the multiple files referring to the same sample but with different data, for example, try to index `file1.vcf` and `file2.vcf`. You have to decide which file to index, because you are supposed to be working with only one set of data per sample at the same time. 

If you have different versions of the genomic data of one sample or individual, and you want to process both at the same time, you will need to split the data into different studies (not the idea) or use a more specific sample name (HG001_v1, HG001_v2, ...) to differentiate the genomic data. Both samples can be linked by sharing the same individual.

**Comment by j-coll** [comment]
At this moment, the check of "do not index the same sample twice" produces a [warning instead an exception](https://github.com/opencb/opencga/commit/48878d5feb81079b79875f0cb7b6a69ec408dc82#diff-1a36edaa0be31d1ee7ab708a7fe79613R345).

This change was made in order to allow loading files about the same sample but of a different genomic region, like the [1000 Genomes Project](http://www.1000genomes.org/), who splits the VCFs by chromosomes. 

This behavior must be restored, and add an option like "--force" or "--allow-repeated-samples".

**Comment by j-coll** [comment]
Now, to load multiple files from the same sample, in different genomic regions, you must add "--load-split-data". 

See #696
