### ISSUE TITLE
CRUD operations for individuals

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#169]
Currently, [`Individual`](https://github.com/opencb/opencga/blob/e810252f62a952d16a29327ecfc413212de1fae9/opencga-catalog/src/main/java/org/opencb/opencga/catalog/models/Individual.java) objects does not have any CRUD operation implemented. 

For this, it's needed to define the `CatalogIndividualDBAdaptor` interface, implement it for MongoBD, the  `IndividualManager` with the authentication and authorization capabilities, and the connection with the `CatalogManager`.

**Comment by j-coll** [comment]
Before implementing this, a small schema change needs to be implemented. Currently, a [`Sample]`(https://github.com/opencb/opencga/blob/e810252f62a952d16a29327ecfc413212de1fae9/opencga-catalog/src/main/java/org/opencb/opencga/catalog/models/Sample.java) contains an `Individual` object. This needs to be changed to an `individualId`, because one individual can be linked by several samples.

Like the list of `Samples` or the list of `Files`, each `Study` will contain a list of `Individuals`

**Comment by imedina** [comment]
Besides, some attributes may be needed in Individual model, a tentative list of attributes could be:

    private int id;
    private String name;
    private int father;
    private int mother;
    private String family;
    private String gender;
    private String race;
    private String population;

    // not sure about the meaning of this parameter
    // private String type;
    
    private Species species;
    private Map<String, Object> attributes;

    // internal class
    class Species {
       private String taxonomyCode;
       private String scientificName;
       private String commonName;
    }

comments?

**Comment by cyenyxe** [comment]
Being a model and a not a DB mapping, I would make "father" and "mother" objects of type Individual, not integers.

I would also say that an individual can belong to more than just one population. Or, since @j-coll says that an individual is linked to multiple samples, then maybe the sample is the one that should belong to one or more populations.

By the way, there is another class [Individual](https://github.com/opencb/biodata/blob/develop/biodata-models/src/main/java/org/opencb/biodata/models/pedigree/Individual.java) in the biodata repository, maybe it would be a good idea to unify OpenCB models under biodata-models...

**Comment by imedina** [comment]
I agree, father and mother must be Individuals in the model. I started doing the requirement specification and I added some types.

Samples belong to a single Individual, for instance from one individual with cancer I can get some DNA from the tumour and form healthy tissue. Both samples belong to the same individual and therefore there is a "single" population to belong to. Am I missing anything?

**Comment by cyenyxe** [comment]
If a pedigree file was provided, the tumour could belong to the "cases" population and the healthy tissue to the "controls".

Also, if multiple pedigree files are created for the same study, they would probably group samples in different ways.

**Comment by j-coll** [comment]
I disagree of having father and mother as Individuals. At this moment, all the connections between catalog models are without loops, what makes easier to serialize in JSON (and, secondarily, save it in the DB).
If we set father and mother Individuals, then, why do not replace all other IDs like `sampleIds` in a file or `variableSetId` in an `AnnotationSet` with the representing object?

**Comment by imedina** [comment]
Pedigree file is aimed to provide "family" information such as family, father, ... it is more a "individual-centric" format than sample-centric. Personally, I have never seen a PED file having different samples from the same individual. I would care too much about PED as it seems that not too many new projects are using that format, it is too simple to capture all the information.

**Comment by cyenyxe** [comment]
@j-coll, then you would be making the model dependant on the serialization format, which is not a good idea...

Maybe for opencga-storage it is not very useful/viable to use an ORM due to how many optimizations are done to store genotypes, but I think opencga-catalog is a great use case. An example of how to define a class with several relationships in Morphia: http://mongodb.github.io/morphia/1.0/getting-started/quick-tour/#mapping-classes At least in JPA it was a very powerful and convenient mechanism.
