### ISSUE TITLE
'Solr server is not alive' error on IVA variant aggregation view

### ISSUE THREAD

**Issue by mwhamgenomics** [opencb/opencga#1698]
Visiting the aggregation view in the variant browser and doing a test query results in the error `Solr server is not alive`:

![Screenshot 2021-01-18 at 12 35 37](https://user-images.githubusercontent.com/12951686/104918317-79483180-598c-11eb-96bd-1dbb59752cdc.png)

I traced this in JDB to `isAlive` in [java-common-libs SolrManager](https://github.com/opencb/java-common-libs/blob/v4.0.3/commons-datastore/commons-datastore-solr/src/main/java/org/opencb/commons/datastore/solr/SolrManager.java#L133), where it pings Solr at `/solr/<collection>/admin/ping` with a collection parameter. I saw that the collection name was being set to the variant database name, i.e. `opencga_<user>_<project>`, so it was pinging `/solr/opencga_<user>_<project>/admin/ping`, finding nothing and reporting that Solr is down. Surely this should be the name of a Solr configset instead? Pinging the database name versus a configset name gives me the results I'd expect:

```
$ curl localhost:8983/solr/opencga_<user>_<project>/admin/ping
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404 Not Found</h2>
<table>
<tr><th>URI:</th><td>/solr/opencga_<user>_<project>/admin/ping</td></tr>
<tr><th>STATUS:</th><td>404</td></tr>
<tr><th>MESSAGE:</th><td>Not Found</td></tr>
<tr><th>SERVLET:</th><td>default</td></tr>
</table>
</body>
</html>
$ curl localhost:8983/solr/opencga-cohort-configset-2.0.0/admin/ping
{
  "responseHeader":{
    ...
    "status":0,
    "params":{
      ...
      "rows":"10",
      "echoParams":"all",
      }},
  "status":"OK"}
```

I can see that [SearchIndexVariantAggregationExecutor](https://github.com/opencb/opencga/blob/v2.0.0/opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/search/SearchIndexVariantAggregationExecutor.java) passes the dbName to VariantSearchManager, which then [passes](https://github.com/opencb/opencga/blob/v2.0.0/opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/search/solr/VariantSearchManager.java#L521) it to SolrManager.getCollection. Is Solr meant to have project names in its collections, or is the wrong parameter being passed?

**Comment by j-coll** [comment]
Hi @mwhamgenomics ,

The solr manager here is checking if the Variant's collection is available. I was already commenting with @pfurio the other day that the message "Solr server is not alive" could be misleading, and in some cases, the actual message should be something like "Solr collection not found - please run secondary index".

I am confused about pinging the configset instead of the collection name. As far as I can see in the Solr documentation, that should not work (unless you have a collection with that specific name). Which solr version do you have? Is it configured in cloud mode? 
https://lucene.apache.org/solr/guide/8_4/ping.html

In order to check if the collection is actually missing (because the secondary index operation was not run), or if there is any other solr issue, could you please list your collections?

```
curl http://localhost:8983/solr/admin/collections?action=LIST
```

**Comment by mwhamgenomics** [comment]
Yes, that makes sense! I was missing the secondary index in that study. I'm running it now, and even though it hasn't finished yet, that page now shows some aggregation stats and no longer gives errors.

I have Solr in standalone mode so that curl command gives me an error saying `Solr instance is not running in SolrCloud mode`, but I think this is sorted out now. At first I was adding configsets with `solr create_core`, before I realised that I should instead just add the configsets to `server/solr/configsets`, and the secondary index will then create collections off of that.

I think everything here is resolved, and the issue should just be for updating the 'server not alive' message to remind the user to run the secondary index. Thanks!
