### ISSUE TITLE
Implement query negations

### ISSUE THREAD

**Issue by imedina** [opencb/opencga#187]
For instance a frequency filter - would need to return variants that are absent from a particular database as well as variants that are below the specified frequency. This could be generalised as the ability to query for negatiions

**Comment by j-coll** [comment]
Just to clarify: Is this query negation trying to solve the problem when filtering by a field that is missing in some variants?
Actually, all the existing filters will discard a variant that does not contain the selected filter. So, the filter `freq<0.2` means *"Variants that contains any value for freq, and freq is lower than 0.2"*, so it is not complementary with `freq>=0.2`.
That means that `freq<0.2`  **!=**  `!(freq>=0.2)`. In some cases, will be interesting to ask for `!(freq>=0.2)` instead of `freq<0.2`

**Comment by j-coll** [comment]
See [Querying Variant Data](https://github.com/opencb/opencga/wiki/Querying-Variant-Data)
