### ISSUE TITLE
user passwords exposed in URL

### ISSUE THREAD

**Issue by mbsimonovic** [opencb/opencga#207]
the new REST API allows for passwords to be sent in URL (hashed but still ):
http://bioinfodev.hpc.cam.ac.uk/opencga/webservices/rest/v1/users/mbsimonovic/login?password=md5HASSSHSH

OAuth might be a bit too much, but maybe this could go over HTTP Digest?

**Comment by j-coll** [comment]
Due to the security of the data hosted on this platform, is highly recommended to use HTTPS for all the communications. In that case, this authentication mechanism will be secure enough.

But, there could be some situations where the HTTPS is not used (demo versions, lack of resources or secure intranets) and for this situations, a more secure authentication method will be required.

**Comment by imedina** [comment]
Let me add that the current installation at University is intended to be a demo, not for hosting real data. This could change in the future when more resources are allocated.
In "real" installations security can be set up in a different ways: firewalls, vpn, https, ...

**Comment by mbsimonovic** [comment]
sure, but at the moment it's publicly available at http://genomemaps.org/ without a warning it's a *demo setup* :)

**Comment by imedina** [comment]
Thanks for your feedback, from version v1.1.0 _login_ is implemented using POST so the password is not longer in the URL
