### ISSUE TITLE
Bug in study variants using annot-ct filter

### ISSUE THREAD

**Issue by Antonior26** [opencb/opencga#274]
It seems there is a big bug here, annot-ct don't select all the the variants it should. surprisingly it works with it is combined with region:

curl -o reg.txt  "http://***.***.**.**/opencga/webservices/rest/v1/studies/1453971/variants/?sid=***************&sort=true&annot-ct=SO:0001893,SO:0001574,SO:0001575,SO:0001587,SO:0001589,SO:0001578,SO:0001582,SO:0001889,SO:0001821,SO:0001822,SO:0001583,SO:0001630,SO:0001626&limit=-1&region=1:111909361-111909361"

curl -o no_reg.txt  "http://***.***.**.**/opencga/webservices/rest/v1/studies/1453971/variants/?sid=***************&sort=true&annot-ct=SO:0001893,SO:0001574,SO:0001575,SO:0001587,SO:0001589,SO:0001578,SO:0001582,SO:0001889,SO:0001821,SO:0001822,SO:0001583,SO:0001630,SO:0001626&limit=-1

It happened to me that the 1:111909361-111909361 variant is appear in the first case but not in the second

**Comment by j-coll** [comment]
I am pretty sure that your problem is with the automatic limit of the server. The server is not able to return all the possible variants of the server in one QueryResponse. It will kill the server (or the client), since the server has to fetch all the data of the query after sending to the client. The current default limit is set to 1000, and there is a maximum limit of 5000. This values are hard-coded until the new configuration file in yaml is finished.

In order to download large sets of variants, you need to paginate the results:

 - First, query the first page and ask for the total result number:
```
variants?skipCount=false&skip=0&limit=2500&...
 >> totalNumResults=20000
```
In the example the pageSize is 2500. With 20000 variants in the result, will require to split the result in 8 queries : `20000/2500=8`

 - variants?skip=2500&limit=2500
 - variants?skip=5000&limit=5000
 - ......
 - ...

This pagination can be really slow for complex queries or extra large datasets. At this moment we are implementing streaming using gRPC servers to connect directly to the internal storage server #247, but this will be extended to the main server.
