### ISSUE TITLE
Restriction and permissions

### ISSUE THREAD

**Issue by apaytuvi** [opencb/opencga#456]
Hi,

I would like
- to prevent that guest users create accounts
- to prevent the user "example" to upload data

How would I do that?

Thank you.

**Comment by pfurio** [comment]
Hi, 

> - to prevent that guest users create accounts:

In order to do that, you will need to modify your catalog-configuration.yml file. If you check there, you will see a parameter called openRegister. You will need to set that one to false. Otherwise, anyone will be able to create a new user account. 

It is important to notice that that parameter is only read when you are installing opencga for the first time, so if you already have it installed, you will need to change it manually from the mongo database. This feature is something we want to implement and add to the admin command line so it can be changed much more easily but it is still not available.

To change it at this point, you will need to:
`# 1. Connect to mongo database`
`# > use "database_name"`
`# > db.metadata.update({},{$set: {open: "private"}})`

Once you do that, the registration will be closed to user and only possible using the opencga-admin.sh command line. 

> to prevent the user "example" to upload data

The list of file permissions can be found in this [link](https://github.com/opencb/opencga/blob/develop/opencga-catalog/src/main/java/org/opencb/opencga/catalog/models/acls/permissions/FileAclEntry.java#L32). Apparently, we forgot about adding the upload permission and almost anyone with study permissions will be able to upload a file. I will add that permission asap.

**Comment by pfurio** [comment]
I just added the upload permission. By default, if the user "example" has not been given any permission, he won't be able to do anything. However, if you just want that user not to have that permission but to have the rest, you will need to do something like:

.opencga.sh studies acl-create --id yourStudyAlias --members example --permissions [all the study permissions except for upload comma separated]

We don't have a way of saying don't give this permission but rather the contrary. With that command line you give some permissions and those not specified will be denied to the user. So if you want the user example to have permission to see the study and the files, you would do it like follows:

./build/bin/opencga.sh studies acl-create --id studyAlias --members example --permissions VIEW_STUDY,VIEW_FILES

The rest of the permissions will be denied. That user won't be able to see samples, individuals... create files, update files, etc.

**Comment by apaytuvi** [comment]
Hi @pfurio 

thank your for your reply. Regarding the first issue, I can't see the key "open":

```
> db.metadata.find()
{ "_id" : ObjectId("583d8184246deebfabee426b"), "downloadDate" : "20161121_163119", "uRL" : [ "ftp://ftp.ensembl.org/pub/release-82/fasta/homo_sapiens/dna/*.dna.primary_assembly.fa.gz" ], "data" : "genome", "source" : "ENSEMBL", "version" : "82_38" }
{ "_id" : ObjectId("583edf21246dee1c13f63815"), "downloadDate" : "20161012_124419", "uRL" : [ "http://dgidb.genome.wustl.edu/downloads/interactions.tsv" ], "data" : "gene", "source" : "DGIdb", "version" : null }
{ "_id" : ObjectId("583edf21246dee1c13f63817"), "downloadDate" : "20161012_124416", "uRL" : [ "ftp://ftp.ensembl.org/pub/release-82/gtf/homo_sapiens/*82.gtf.gz", "ftp://ftp.ensembl.org/pub/release-82/fasta/homo_sapiens/pep/*.pep.all.fa.gz", "ftp://ftp.ensembl.org/pub/release-82/fasta/homo_sapiens/cdna/*.cdna.all.fa.gz", "ftp://ftp.ensembl.org/pub/release-82/regulation/homo_sapiens/MotifFeatures.gff.gz" ], "data" : "gene", "source" : "ENSEMBL", "version" : "82_38" }
{ "_id" : ObjectId("583edf21246dee1c13f63819"), "downloadDate" : "20161012_124429", "uRL" : [ "ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/idmapping/by_organism//HUMAN_9606_idmapping_selected.tab.gz" ], "data" : "gene", "source" : "UniProt", "version" : "2016_09" }
{ "_id" : ObjectId("583edf21246dee1c13f6381b"), "downloadDate" : "20160815_161237", "uRL" : [ "ftp://ftp.ebi.ac.uk/pub/databases/microarray/data/gxa/allgenes_updown_in_organism_part_2.0.14.tab.gz" ], "data" : "gene", "source" : "Gene Expression Atlas", "version" : "2.0.14" }
{ "_id" : ObjectId("583edf21246dee1c13f6381d"), "downloadDate" : "20161012_124430", "uRL" : [ "http://compbio.charite.de/hudson/job/hpo.annotations.monthly/lastStableBuild/artifact/annotation/ALL_SOURCES_ALL_FREQUENCIES_diseases_to_genes_to_phenotypes.txt" ], "data" : "gene", "source" : "HPO", "version" : null }
{ "_id" : ObjectId("583edf21246dee1c13f6381f"), "downloadDate" : "20161012_124433", "uRL" : [ "http://www.disgenet.org/ds/DisGeNET/results/all_gene_disease_associations.tsv.gz" ], "data" : "gene_disease_association", "source" : "DisGeNET", "version" : "version 4.0, June 2016" }
```

I am using opencga hotfix-0.7.

Regarding the second issue, whould I update opencga to develop branch in order to do so?

**Comment by pfurio** [comment]
Hi @apaytuvi. Sorry for the delay.

I thought you were using the latest develop version already. You would need to upgrade to that version if you want that. However, since 0.7 we have applied many many changes and improvements (not only implementation but also changes in data models) so you would need to do a new installation and start populating the database again from scratch.
