### ISSUE TITLE
end position = start position - 1

### ISSUE THREAD

**Issue by dnafault** [opencb/opencga#461]
I noticed that for INDEL variants pretty often  end position = start position -1
This is wrong.

**Comment by dnafault** [comment]
see screenshot
![screenshot from 2016-12-06 22-06-12](https://cloud.githubusercontent.com/assets/20377386/20948869/6b8f821e-bc6a-11e6-9afc-60e9763bd0d2.png)
.

**Comment by j-coll** [comment]
Hi @dnafault 

The Variant model of Biodata uses positions in 1-based system, inherited from the VCF specification. Start and end positions refer to positions in the reference genome (an insertion of 30 bases will have the same end as an insertion of 100 bases, for example). Therefore, the definition of the end position is :
 `start + reference.length() - 1`

To understand this definition we have to be aware of the inclusion-exclusion of the intervals. In 1-based, intervals are (usually) closed, so the start and the end are inclusive: `[start, end]` . In 0-based systems, the end is exclusive, so it's defined as [start, end). 

```
1-based:
    interval = [start, end]
    length = end - start + 1
    end = start + length - 1

0-based:
    interval = [start, end)
    length = end - start
    end = start + length
```

To avoid this situation, the VCF specification forces that all the alleles to be non-empty, so the reference.length is at least 1.
GA4GH takes a different approach, they decide to allow empty alleles use variant positions in 0-based system, so the end is defined as : `start + reference.length`

On the other hand, Ensembl allows empty alleles and uses 1-based position system. We can see this, the deletions that they provide:

`Location    Chromosome 6: between 9900599 and 9900600 ` for [rs59046538](http://grch37.ensembl.org/Homo_sapiens/Variation/Explore?db=core;r=6:9900100-9901099;v=rs59046538;vdb=variation;vf=114483770)
Internally, they are storing 9900600 as the start and 9900599 as the end.

Let me open a ticket in Biodata to review the documentation regarding this point: [#136](https://github.com/opencb/biodata/issues/136)

**Comment by dnafault** [comment]
Thanks for comprehensive explanation Jacobo, really appreciate.

So Biodata stores variants as 1-based and uses definitions from 1-based system but deliberately violates boundary conditions of this system by transforming variants from VCF in such a way that excludes reference allele from ALT, making REF = null and changing a start position for ALT.

This decision (subtracting REF from ALTs) leads not only to nonsense like end < start, but also changes ALTs from the form they were called in original VCFs. This doesn't make much sense to me. Anyway, thanks again for explanation.

**Comment by j-coll** [comment]
Hi,

Yes, we are "violating" some restrictions from the VCF that are, from our point of view, unnecessary restrictions. In OpenCGA, we are not storing VCFs. We store variants that came from a VCF.

As I said, we are using the same definition as ensembl: http://www.ensembl.org/info/docs/tools/vep/vep_formats.html

We are doing this in the context of Variant Normalization, which is mandatory in order to identify when two variants are the same. Please, found more information here:

- http://bioinformatics.oxfordjournals.org/content/early/2015/02/19/bioinformatics.btv112.short
- https://github.com/opencb/opencga/wiki/Variant-Normalization

Any case, we know that some people may need the original call. We are always storing the original call for a variant in the [FileEntry](https://github.com/opencb/biodata/blob/develop/biodata-models/src/main/avro/variant.avdl#L112). We are storing this in the FileEntry and not in the StudyEntry or the Variant because it may happen that different VCF variants ends up to be the same variant like:

```
chr1  .  100  A  AT
chr1  .  101  C  TC
```

Supposing that they came from different files, that will end up in this:
```javascript
{
  chromosome : "1",
  start : "101",
  end : "100",
  studies: [
    files : [
      { fileId: 1, call : "100:A:AT:0" },
      { fileId: 2, call : "101:C:TC:0" }
    ]
  ]
}
```
