### ISSUE TITLE
Missing web services: files/link

### ISSUE THREAD

**Issue by Philip-Wu** [opencb/opencga#531]
Version release-1.0.0.-final

Previous versions had the web service for files/link. But the latest version appears not to support it in the swagger interface

How can we bring it back? Is this a bug?

**Comment by pfurio** [comment]
Hi Philip-Wu. This has been done intentionally and is not a bug. 

OpenCGA is designed to work in clusters so many people from a research department can all access the same installation. In this scenario, sysadmins would create the Opencga installation and normal users would not have access to the server, so in order to avoid possible authorization problems, we have removed that option from the webservices.

On the other hand, maybe you have realised that that option is still available from the opencga.sh command line. This is fully intentional because if one user can access the server and the database where opencga is installed, the user should be able to link any file/folder the user might have direct access to. However, this is one exception as it is the only subcommand that will not work from any place because it won't access the webservices and will attempt to connect with the database directly.

**Comment by Philip-Wu** [comment]
Thanks Pedro for the explanation and makes sense, but I have a use case that requires me to programmatically link files to studies. And to execute command line to do the imports is rather difficult and clunky as I need a session ID which requires I login via the command line with a prompt to enter the password.

Is there another recommended way to do this? I would prefer using the web service if possible. We plan to use opencga as a backend service, so our users would not have direct access to opencga.

How hard would it be to restore this web service if I made my own custom build? I'm a seasoned java developer and not afraid to dig into the code


Thanks

Phil



On 22 Feb. 2017 10:47 pm, Pedro Furió <notifications@github.com> wrote:

Hi Philip-Wu. This has been done intentionally and is not a bug.

OpenCGA is designed to work in clusters so many people from a research department can all access the same installation. In this scenario, sysadmins would create the Opencga installation and normal users would not have access to the server, so in order to avoid possible authorization problems, we have removed that option from the webservices.

On the other hand, maybe you have realised that that option is still available from the opencga.sh command line. This is fully intentional because if one user can access the server and the database where opencga is installed, the user should be able to link any file/folder the user might have direct access to. However, this is one exception as it is the only subcommand that will not work from any place because it won't access the webservices and will attempt to connect with the database directly.

**Comment by Philip-Wu** [comment]
I've found a way to restore the function quite easily in the source code with a one line change.
In the project folder opencga-server, serach for the file: **org.opencb.opencga.server.rest.FileWSServer.java**

Simply remove the hidden attribute called 'hidden' of the ApiOperation annotation

from

```
    @GET
    @Path("/link")
    @ApiOperation(value = "Link an external file into catalog.", hidden = true, position = 19, response = QueryResponse.class)
```
Change to:

    @GET
    @Path("/link")
    @ApiOperation(value = "Link an external file into catalog.", position = 19, response = QueryResponse.class)


Cheers
