### ISSUE TITLE
Command and rest endpoints for remove operations on variant storage

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#623]
Since #487, deleting operations on variant storage (studies, files, annotation and statistics) are high level operations in the VariantStorageEngine.

But this methods are now only accessible programmatically. We need to add rest endpoints and commands in the tree command lines (opencga.sh, opencga-analysis.sh and opencga-storage.sh).

* Requires:  #192 

**Tasks list:**

- [x] opencga-analysis.sh variant remove
- [x] opencga-storage.sh variant remove
- <strike> Endpoint `analysis/variant/remove` </strike>
- <strike> opencga.sh variant remove </strike>

**Comment by j-coll** [comment]
@imedina , could you please check the names for the endpoints and commands?

**Comment by imedina** [comment]
They look fine to me. I guess the parameters will be something like:

`opencga.sh variant remove -s STUDY --file FILE.VCF`

to remove a specific file or just this to remove all files from one study:

`opencga.sh variant remove -s STUDY --file all`

I prefer to add `--file all`, otherwise can be error prone.

**Comment by j-coll** [comment]
I like the `--file all`. It is a dangerous operation.

And what about deleting statistics and annotation?
