### ISSUE TITLE
Make ACL permissions part of the query

### ISSUE THREAD

**Issue by imedina** [opencb/opencga#628]
Current implementation applies ACL permission check after quer query, no during the query, this makes all the web services to return incorrect results when paging.

**Comment by pfurio** [comment]
To do so, we will need to change the current implementation so the objects are now retrieved based on the permissions every user have instead of fetching everything matching the query and filtering data manually afterwards.

The main implication of this action is that the dbAdaptors will have to be able to build the corresponding query taking care of the Acls instead of having this functionality in the managers layer.
