### ISSUE TITLE
Admin Account

### ISSUE THREAD

**Issue by nicholsn** [opencb/opencga#652]
Hi,
I built opencga from the master branch and completed successfully and I can access the swagger pages. However, I am not able to login or create new users and am getting the following error:

```
15:45 $ ./bin/opencga.sh users login -u admin -p
User password:
org.opencb.opencga.catalog.exceptions.CatalogException: Bad user or password
	at org.opencb.opencga.client.rest.OpenCGAClient.login(OpenCGAClient.java:163)
	at org.opencb.opencga.app.cli.main.executors.catalog.UserCommandExecutor.login(UserCommandExecutor.java:111)
	at org.opencb.opencga.app.cli.main.executors.catalog.UserCommandExecutor.execute(UserCommandExecutor.java:88)
	at org.opencb.opencga.app.cli.main.OpencgaMain.main(OpencgaMain.java:118)
```

I tried setting the default password in `conf/configuration.yml` but to no avail. Any idea what I am doing wrong here?

Looks like an interesting project and looking forward to checking it out! Thanks!

**Comment by pfurio** [comment]
Hi Nolan,

OpenCGA comes some additional command lines apart from the opencga.sh as can be seen here http://docs.opencb.org/display/opencga/Command+Lines. For starters, you will need to run the proper admin command line to install the OpenCGA database together with the proper indexes:

//Here you not only install OpenCGA but also define a password for the admin

> ./opencga-admin.sh catalog install -p

After that, if the registration is open to the public, users will be able to register themselves by running:

> ./opencga.sh users create xxxx

Otherwise, the admin will need to create those accounts by running:

> ./opencga-admin.sh users create xxx -p

Once a user account has been created, it will be possible to login the way you were trying to do. Just remind you that all the things the admin can do are done using the opencga-admin.sh command line and all the actions normal users can do are done using the other opencga.sh command line.

Here you can find a quick tutorial explaining exactly that: http://docs.opencb.org/display/opencga/Getting+Started+in+5+minutes

Hope it helps. Please let me know if you have more doubts.

**Comment by nicholsn** [comment]
@pfurio, thank you for this info! I can confirm I was able to login and get things started.

I did not come across the Confluence wiki docs and was confused because the READMD.md file still points to the Github Wiki page. It would be great if you could update that so folks get the latest docs, which look really nice BTW!
