### ISSUE TITLE
Annotation Endpoint

### ISSUE THREAD

**Issue by nicholsn** [opencb/opencga#656]
I'm following the 'Setting Started in 5 Minutes' tutorial and have opencga up an running. I am able to complete all the commands in the tutorial, except for the annotation step where I am getting the following error:

```
./opencga-analysis.sh variant annotate -s 1kG_phase3 -o /tmp/temporal_annotation -v
...
2017-07-25 08:39:09 [pool-2-thread-8] DEBUG VariantClient:342 - Making POST call to REST URL: http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/latest/hsapiens/genomic/variant/annotation?exclude=expression&limit=1000
2017-07-25 08:39:10 [pool-2-thread-6] WARN  VariantClient:259 - CellBase REST fail. Error parsing query result for ids 22:16145400:C:A,
...
```

It looks like the REST endpoint is down at `http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/latest/hsapiens/genomic/variant/annotation?exclude=expression&limit=1000`... Is that to be expected? 

Is there another cellbase endpoint that is up? If so, how would I configure my client to hit that endpoint?

Thanks!

**Comment by j-coll** [comment]
Hi @nicholsn ,

The problem is with the cellbase version `latest`. As you can see in the URL, it is calling to .../cellbase/webservices/rest/**latest**/hsapiens/....

The tag `latest` for the version is not well supported, and is not recommended. Is better to use `v4`

Cellbase version can be configured directly in the `storage-configuration.yml`, or through the maven profile at the `settings.xml` modifying the property `<OPENCGA.CELLBASE.VERSION>v4</OPENCGA.CELLBASE.VERSION>`

How did you end up using "latest" as the cellbase version?

**Comment by nicholsn** [comment]
Hey @j-coll,

I deployed the prebuilt binary 1.1.1 from https://github.com/opencb/opencga/releases/tag/v1.1.1 and the `latest` endpoint was the default.

Updated to v4 and now its annotating away. Thanks!
