### ISSUE TITLE
Configure Index Pipeline to Use cellbase_db_adaptor

### ISSUE THREAD

**Issue by nicholsn** [opencb/opencga#753]
How do I go about configuring `storage-configuration.yml` so that the full Index Pipeline will use the `cellbase_db_adaptor` to hit my local cellbase mongodb rather than my local `cellbase_rest` annotator?

I've tried setting `storage-configuration.yml` to the following, but to no avail: 

```
variant:
    ...
    options:
      ...
      annotator: cellbase_db_adapt
```

This is how I am calling the Index pipeline:
```
./opencga.sh variant index --file my_study.vcf.gz --calculate-stats --annotate --outdir outDir --study my_study
```

Is there a way to explicitly pass `cellbase_db_adaptor` similar to how you would in ./opencga-analysis.sh?

Other suggestions? Thanks!

**Comment by j-coll** [comment]
Hi @nicholsn ,

We detected an issue with that configuration parameter one week ago. Internally, the code is looking for the parameter "annotationSource" instead of "annotator".

This is fixed for version 1.3.0 at #747. Meanwhile, add "`annotationSource: cellbase_db_adaptor`" to the storage-configuration.yml
