### ISSUE TITLE
Allow to create families with no fathers and/or mothers

### ISSUE THREAD

**Issue by jpflorido** [opencb/opencga#755]
It would be useful if a familiar analysis is created even if there are no fathers or mothers. For example, a familiar analysis with just Siblings. The use of fathers and mothers should not be mandatory. This way, bigger families can be created with "distant" family members (cousins or uncles) even if pedigree does not support this type of families.

A family can not be created if there are no father or mother and, as a consequence, an analysis can not be created.

So, create family web service can be modified to allow members in which the parental relationships are not specified.

**Comment by Antonior26** [comment]
Javi, you should not been able to do that. A family should be define as a closed graph always, if you have to siblings in the family with no parents, you can't know that they are siblings, the only way to reconstruct the relationship is based on the parents (in the sibling example, both participants will share the same parents).  You remember that in opencga you can create a individual without samples, so the right way in my opinion to solve your problem is create "dummy" parents with no samples. If you do it in this way and the analysis is well implemented distant relationships as (uncles) can be perfectly reconstructed from these types of closed pedigrees.

**Comment by jdopazob** [comment]
Antonio, from a purely practical standpoint I do not agree. While your suggestion is conceptually nice it introduces a practical complexity in the management of the analyses and, for many end users involves an extra complexity in the usage (what if it is a third degree cousin?, you will need a number of dummy relatives)
My suggestion is: for the family analysis we should allow anything ranging from a completely defined pedigree to a collection of disconnected individuals. If the pedigree covers every individual, then we can automatically deduce the segregation along the family, if not, the user has to define it by hand, using the " Select Sample Genotypes:" from the priorotization/study submenu. 
A common way of proceeding in our users is to start with the analysis of only one individual and if unsuccessful, then keep adding other familiars for subsequent analyses, not necessarily direct relatives. Then the family relationships among samples are defined in subsequent analyses. For example, NaGen prefers affected second cousins or similar to increase the chances of finding good candidates.    
I think this way of implementing the analysis is almost immediate and involves less complexity. You define family relationships as you add direct relatives. Then, for the family analysis, if all the individuals are within the pedigree, the segregation can be automated, otherwise it can be manually defined using the "Select sample genotypes" option.
That would lead to remove the restriction of >3 individuals for a family analysis (e.g. a two-brother analysis is not the same than a duet). Actually, I am strongly tempted to suggest the removal of duet and trio and only leave family (but this is another thread).

**Comment by imedina** [comment]
Although I'm more on the side of @Antonior26 I think there is an easy solution to make everybody happy, we can just add a new _allowDisconnected_ parameter to the _create_ family method, this will control whether we check disconnected members or not.
@jpflorido @jdopazob be aware that OpenCGA we will not keep any information of those members if parents are not set.

**Comment by Antonior26** [comment]
Yes, I see your problem @jdopazob @jpflorido, in fact I was thinking purely in a automatised analysis, but if you have the options to select the genotypes you want to filter (or select) that of course would work just fine.  Probably I will called that a cohort rather than a family, but 100% happy with Nacho suggestion.

**Comment by jpflorido** [comment]
Thank you guys for this nice discussion. I'm happy with Nacho's solution, so let's do it!

**Comment by jdopazob** [comment]
Actually, it is not incompatible with the @Antonior26 suggestion, that can be later implemented. But with @imedina solution we can address all these brother/cousin/uncle/whatever scenarios right now.
Even if relatives are unconnected in an initial analysis, they can be conencted in future analysis if more relatives that connect them are added
