### ISSUE TITLE
Update Protobuf to 3.2.0?

### ISSUE THREAD

**Issue by nicholsn** [opencb/opencga#762]
Running an older version of redhat, protobuf version 3.1.0 is not available on maven. To compile opencga, I had to bump the version to `3.2.0` in pom.xml.

```
<google.protobuf>3.2.0</google.protobuf>
```

Is there any harm in using `3.2.0` as the default?

**Comment by imedina** [comment]
I think is a pretty safe change since v1.2.0. In the past this was causing some problems with HBase protobuf version I think, but since OpenCGA 1.2.0 all Hadoop versions are shaded so it should be safe. @j-coll do you agree with this?

If yes I will create a ticket to upgrade both gRPC and ProtoBuf in next 1.4.0.

**Comment by imedina** [comment]
Finally this has been upgraded to grpc 1.9.1 which uses protobuf 3.5.1
