### ISSUE TITLE
Access to single sample in Opencga command not working!

### ISSUE THREAD

**Issue by Mohammedhusen** [opencb/opencga#884]
Hi ,

I need to provide access to single sample I tried using below command which gives an error.

Command:
opencga.sh samples acl-create --id 123 --members user1 --permissions VIEW -s  Test_Project:Test_study

Error:

"Expected a command, got acl-create"

Please help.

**Comment by pfurio** [comment]
Hi,

the command to give permissions was changed. Documentation needs to be upgraded to explain this. Now you can do the same running the following:

opencga.sh samples acl-update --id 123 --members user1 --permissions VIEW -s Test_Project:Test_study --action {SET|ADD|REMOVE|RESET}

The action meaning is the following:
- SET to apply the permissions you add in the permissions field. Any permissions that the user might have had will be removed. So if your user1 already had VIEW_ANNOTATIONS permissions for example and you run the above command line, user1 will no longer have VIEW_ANNOTATIONS permissions and will have VIEW permissions from that moment on.
- ADD  to add the permissions you add in the permissions field without removing any old permissions. Following the prior example, user1 will end up having VIEW and VIEW_ANNOTATIONS permissions.
- REMOVE to remove the permissions you add in the permissions field. Let's say you run the above command with REMOVE, it won't actually apply any change because user1 did not have VIEW permissions. But if you run the same with VIEW_ANNOTATIONS, it will remove that permission.
- RESET to remove all possible permissions user1 had. In this case, you don't need to provide any permission the _permissions_ field. If you run RESET, any permissions that user might have had will be removed.

Hope this helps :)

**Comment by Mohammedhusen** [comment]
Thanks a lot Pedro Furió for your quick help, it solved my issue.
