### ISSUE TITLE
Define coding style guide

### ISSUE THREAD

**Issue by cyenyxe** [opencb/opencga#99]
We should define a coding style guide that everybody could set up in their IDE of preference. Some documents we may use as reference are:

* Oracle's official: http://www.oracle.com/technetwork/java/codeconvtoc-136057.html (old but still applies)
* Google's: https://google-styleguide.googlecode.com/svn/trunk/javaguide.html

I would take the official style and modify some options we might prefer from Google's.

**Comment by imedina** [comment]
Since most of the developers use IntelliJ one option could be to use the default style which I like. Find attached some screenshots:

![intellij_1](https://cloud.githubusercontent.com/assets/1427327/7489603/7d48a6ca-f3d0-11e4-9edb-04562c112b32.png)
![intellij_2](https://cloud.githubusercontent.com/assets/1427327/7489606/7d4b6176-f3d0-11e4-9c1f-9791729e6948.png)
![intellij_3](https://cloud.githubusercontent.com/assets/1427327/7489604/7d49c672-f3d0-11e4-9816-58998779937f.png)
![intellij_4](https://cloud.githubusercontent.com/assets/1427327/7489607/7d50bb4e-f3d0-11e4-8759-244c8c61d835.png)
